name: belanja
description: Aplikasi daftar barang belanja
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/11.jpg
    - assets/12.jpg
    - assets/13.jpg
    - assets/14.jpeg
    - assets/15.jpg
    - assets/16.jpg
    - assets/image/
 
    # Anda bisa menambahkan lebih banyak gambar di sini jika diperlukan

